---
- name: Install Python, Flask and deploy app.py
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Python3 and pip
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask and dependencies using pip
      pip:
        name:
          - flask
          - psycopg2-binary
          - azure-storage-blob
        state: present

    - name: Create directory for application
      file:
        path: /opt/flask_app
        state: directory
        mode: '0755'

    - name: Copy application files to remote server
      copy:
        src: "{{ item }}"
        dest: "/opt/flask_app/{{ item }}"
        mode: '0644'
      loop:
        - app.py
        - requirements.txt

    - name: Create environment file for Flask app
      copy:
        content: |
          # Configuration de l'application Flask
          DB_HOST={{ db_host | default('localhost') }}
          DB_NAME={{ db_name | default('sbeldb') }}
          DB_USER={{ db_user | default('dbadmin') }}
          DB_PASS={{ db_pass | default('SecurePass123!') }}
          STORAGE_ACCOUNT_NAME={{ storage_account_name | default('sbelstorage') }}
          STORAGE_ACCOUNT_KEY={{ storage_account_key | default('') }}
          CONTAINER_NAME={{ container_name | default('staticfiles') }}
          FLASK_ENV=production
        dest: /opt/flask_app/.env
        mode: '0600'
        owner: root
        group: root

    - name: Create systemd service file for Flask app
      copy:
        content: |
          [Unit]
          Description=Flask Application - Démo Cloud
          After=network.target

          [Service]
          Type=simple
          User=root
          Group=root
          WorkingDirectory=/opt/flask_app
          Environment="PATH=/usr/local/bin:/usr/bin:/bin"
          EnvironmentFile=/opt/flask_app/.env
          ExecStart=/usr/bin/python3 -u /opt/flask_app/app.py
          Restart=always
          RestartSec=10
          StandardOutput=journal
          StandardError=journal
          SyslogIdentifier=flask-app
          TimeoutStartSec=30

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/flask-app.service
        mode: '0644'

    - name: Change ownership of flask app directory to match service user
      file:
        path: /opt/flask_app
        owner: root
        group: root
        recurse: yes

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Flask application service
      systemd:
        name: flask-app
        enabled: yes
        state: started

    - name: Install UFW
      apt:
        name: ufw
        state: present
      when: ansible_os_family == "Debian"

    - name: Disable UFW to ensure it doesn't block connections
      ufw:
        state: disabled
      when: ansible_os_family == "Debian"

    - name: Check if SELinux is installed
      command: which selinuxenabled
      register: selinux_check
      failed_when: false
      changed_when: false

    - name: Set SELinux to permissive if installed
      command: setenforce 0
      when: selinux_check.rc == 0
      failed_when: false
      changed_when: false

    - name: Install netstat for debugging
      apt:
        name: net-tools
        state: present
      when: ansible_os_family == "Debian"

    - name: Check if Flask service is running
      command: systemctl status flask-app
      register: service_status
      changed_when: false
      failed_when: false

    - name: Display Flask service status
      debug:
        var: service_status.stdout_lines

    - name: Check listening ports
      command: netstat -tulpn
      register: netstat_output
      changed_when: false

    - name: Display listening ports
      debug:
        var: netstat_output.stdout_lines

    - name: Restart Flask service
      systemd:
        name: flask-app
        state: restarted

    - name: Ensure Flask is accessible
      wait_for:
        port: 5000
        host: 0.0.0.0
        timeout: 30
        state: started

    - name: Copy sample data script
      copy:
        src: sample_data.sql
        dest: /opt/flask_app/sample_data.sql
        owner: root
        group: root
        mode: '0644'

    - name: Wait for application to be ready
      wait_for:
        port: 5000
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 60

    - name: Verify application is accessible
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:5000/health"
        method: GET
        timeout: 30
      register: health_check
      retries: 5
      delay: 10
      until: health_check.status == 200

    - name: Load sample data (optional)
      postgresql_query:
        db: "{{ db_name }}"
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_pass }}"
        query: "{{ lookup('file', '/opt/flask_app/sample_data.sql') }}"
      ignore_errors: yes
      tags: sample_data

    - name: Display application access information
      debug:
        msg:
          - "🚀 Application Flask déployée avec succès!"
          - "📍 Accès: http://{{ ansible_default_ipv4.address }}:5000"
          - "📊 Monitoring: http://{{ ansible_default_ipv4.address }}:5000/health"
          - "📁 API Files: http://{{ ansible_default_ipv4.address }}:5000/files"
          - "☁️  Test Storage: http://{{ ansible_default_ipv4.address }}:5000/test-storage"
          - "📋 Logs: sudo journalctl -u flask-app -f"
